language: node_js
sudo: false
node_js:
  - "8.11"
install:
  - npm install
  - npm install -g codecov
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
